airport_to_country = {
    'AAL': 'Denmark',
    'AAN': 'United Arab Emirates',
    'ABV': 'Nigeria',
    'ABZ': 'United Kingdom',
    'ACC': 'Ghana',
    'ACE': 'Spain',
    'ACY': 'United States',
    'ADB': 'Turkey',
    'AGP': 'Spain',
    'AHO': 'Italy',
    'ALC': 'Spain',
    'ALG': 'Algeria',
    'ALI': 'United States',
    'AMM': 'Jordan',
    'AMS': 'Netherlands',
    'ANR': 'Belgium',
    'AOI': 'Italy',
    'APF': 'United States',
    'ARH': 'Russia',
    'ARN': 'Sweden',
    'ARW': 'Romania',
    'ATH': 'Greece',
    'ATL': 'United States',
    'AUS': 'United States',
    'AYT': 'Turkey',
    'BBU': 'Romania',
    'BCL': 'Costa Rica',
    'BCN': 'Spain',
    'BDL': 'United States',
    'BDS': 'Italy',
    'BEG': 'Serbia',
    'BEI': 'Ethiopia',
    'BER': 'Germany',
    'BES': 'France',
    'BEV': 'Israel',
    'BEY': 'Lebanon',
    'BFS': 'United Kingdom',
    'BGO': 'Norway',
    'BGR': 'United States',
    'BGY': 'Italy',
    'BHD': 'United Kingdom',
    'BHM': 'United States',
    'BHX': 'United Kingdom',
    'BIA': 'France',
    'BIO': 'Spain',
    'BJL': 'Gambia',
    'BJS': 'China',
    'BJZ': 'Spain',
    'BKK': 'Thailand',
    'BLL': 'Denmark',
    'BLQ': 'Italy',
    'BMA': 'Sweden',
    'BOD': 'France',
    'BOG': 'Colombia',
    'BOS': 'United States',
    'BQT': 'Belarus',
    'BRI': 'Italy',
    'BRN': 'Switzerland',
    'BRS': 'United Kingdom',
    'BRU': 'Belgium',
    'BSL': 'Switzerland',
    'BTS': 'Slovakia',
    'BUD': 'Hungary',
    'BUE': 'Argentina',
    'BUH': 'Romania',
    'BVA': 'France',
    'BWE': 'Germany',
    'BZG': 'Poland',
    'BZV': 'Republic of the Congo',
    'BZZ': 'United Kingdom',
    'CAG': 'Italy',
    'CAI': 'Egypt',
    'CCO': 'Colombia',
    'CCS': 'Venezuela',
    'CDG': 'France',
    'CEK': 'Russia',
    'CFU': 'Greece',
    'CGD': 'China',
    'CGN': 'Germany',
    'CIA': 'Italy',
    'CLJ': 'Romania',
    'CLO': 'Colombia',
    'CLT': 'United States',
    'CMN': 'Morocco',
    'CPH': 'Denmark',
    'CRA': 'Romania',
    'CRL': 'Belgium',
    'CTA': 'Italy',
    'CVG': 'United States',
    'CWL': 'United Kingdom',
    'CZL': 'Algeria',
    'DBV': 'Croatia',
    'DJE': 'Tunisia',
    'DKR': 'Senegal',
    'DLH': 'United States',
    'DME': 'Russia',
    'DOH': 'Qatar',
    'DOK': 'Ukraine',
    'DRS': 'Germany',
    'DSS': 'Senegal',
    'DTM': 'Germany',
    'DTW': 'United States',
    'DUB': 'Ireland',
    'DUS': 'Germany',
    'DXB': 'United Arab Emirates',
    'EAS': 'Spain',
    'EDI': 'United Kingdom',
    'EDPN': 'Germany',
    'EDVN': 'Germany',
    'EGO': 'Russia',
    'EIN': 'Netherlands',
    'EMA': 'United Kingdom',
    'EOH': 'Colombia',
    'ERH': 'Morocco',
    'ESB': 'Turkey',
    'EUN': 'Western Sahara',
    'EVE': 'Norway',
    'EVN': 'Armenia',
    'EWR': 'United States',
    'EXT': 'United Kingdom',
    'EZE': 'Argentina',
    'FAB': 'United Kingdom',
    'FAE': 'Faroe Islands',
    'FAO': 'Portugal',
    'FCO': 'Italy',
    'FEZ': 'Morocco',
    'FLL': 'United States',
    'FLR': 'Italy',
    'FMM': 'Germany',
    'FNC': 'Portugal',
    'FRA': 'Germany',
    'FUE': 'Spain',
    'GCI': 'United Kingdom',
    'GDN': 'Poland',
    'GGW': 'United States',
    'GLA': 'United Kingdom',
    'GOA': 'Italy',
    'GOJ': 'Russia',
    'GOT': 'Sweden',
    'GRU': 'Brazil',
    'GRX': 'Spain',
    'GSE': 'Sweden',
    'GVA': 'Switzerland',
    'GYD': 'Azerbaijan',
    'HAJ': 'Germany',
    'HAM': 'Germany',
    'HAV': 'Cuba',
    'HEL': 'Finland',
    'HER': 'Greece',
    'HEW': 'Greece',
    'HHN': 'Germany',
    'HKG': 'Hong Kong',
    'HUY': 'United Kingdom',
    'IAD': 'United States',
    'IAH': 'United States',
    'IAS': 'Romania',
    'IBZ': 'Spain',
    'ICN': 'South Korea',
    'IEV': 'Ukraine',
    'IKA': 'Iran',
    'IKT': 'Russia',
    'ILD': 'Spain',
    'ISB': 'Pakistan',
    'IST': 'Turkey',
    'IVL': 'Finland',
    'JER': 'United Kingdom',
    'JFK': 'United States',
    'JMK': 'Greece',
    'JNB': 'South Africa',
    'JTR': 'Greece',
    'KBP': 'Ukraine',
    'KEF': 'Iceland',
    'KGD': 'Russia',
    'KGL': 'Rwanda',
    'KGS': 'Greece',
    'KIV': 'Moldova',
    'KJA': 'Russia',
    'KRK': 'Poland',
    'KRR': 'Russia',
    'KRS': 'Norway',
    'KSC': 'Slovakia',
    'KTT': 'Finland',
    'KTW': 'Poland',
    'KUF': 'Russia',
    'KUL': 'Malaysia',
    'KUN': 'Lithuania',
    'KZN': 'Russia',
    'LAS': 'United States',
    'LAX': 'United States',
    'LBA': 'United Kingdom',
    'LBC': 'Germany',
    'LBG': 'France',
    'LCA': 'Cyprus',
    'LCG': 'Spain',
    'LCJ': 'Poland',
    'LCY': 'United Kingdom',
    'LDE': 'France',
    'LED': 'Russia',
    'LEI': 'Spain',
    'LEJ': 'Germany',
    'LEN': 'Spain',
    'LEY': 'Netherlands',
    'LFBO': 'France',
    'LFCS': 'France',
    'LFDY': 'France',
    'LFKL': 'France',
    'LFRR': 'France',
    'LGG': 'Belgium',
    'LGSR': 'Greece',
    'LGW': 'United Kingdom',
    'LHE': 'Pakistan',
    'LHR': 'United Kingdom',
    'LIAU': 'France',
    'LICP': 'Italy',
    'LIG': 'France',
    'LIL': 'France',
    'LIM': 'Peru',
    'LIMA': 'Italy',
    'LIME': 'Italy',
    'LIN': 'Italy',
    'LIPH': 'Italy',
    'LIPS': 'Italy',
    'LIPV': 'Italy',
    'LIS': 'Portugal',
    'LJU': 'Slovenia',
    'LKL': 'Lithuania',
    'LNZ': 'Austria',
    'LON': 'United Kingdom',
    'LPA': 'Spain',
    'LPL': 'United Kingdom',
    'LPLG': 'Portugal',
    'LSMD': 'Switzerland',
    'LTN': 'United Kingdom',
    'LUX': 'Luxembourg',
    'LUZ': 'Poland',
    'LXR': 'Egypt',
    'LYN': 'France',
    'LYO': 'France',
    'LYS': 'France',
    'MAD': 'Spain',
    'MAH': 'Spain',
    'MAN': 'United Kingdom',
    'MCO': 'United States',
    'MEX': 'Mexico',
    'MGL': 'Germany',
    'MIA': 'United States',
    'MIL': 'Italy',
    'MJV': 'Spain',
    'MLA': 'Malta',
    'MLK': 'Germany',
    'MLN': 'Spain',
    'MMX': 'Sweden',
    'MOW': 'Russia',
    'MRS': 'France',
    'MRV': 'Russia',
    'MSP': 'United States',
    'MSQ': 'Belarus',
    'MSR': 'Turkey',
    'MST': 'Netherlands',
    'MUC': 'Germany',
    'MVD': 'Uruguay',
    'MXF': 'United States',
    'MXP': 'Italy',
    'NAP': 'Italy',
    'NAV': 'Turkey',
    'NCE': 'France',
    'NCL': 'United Kingdom',
    'NDR': 'Morocco',
    'NGO': 'Japan',
    'NQT': 'United Kingdom',
    'NRN': 'Germany',
    'NRT': 'Japan',
    'NTE': 'France',
    'NUE': 'Germany',
    'NYC': 'United States',
    'NYO': 'Sweden',
    'OAK': 'United States',
    'OJAF': 'Jordan',
    'OLB': 'Italy',
    'OMS': 'Russia',
    'ONT': 'United States',
    'OPO': 'Portugal',
    'ORA': 'Algeria',
    'ORD': 'United States',
    'ORK': 'Ireland',
    'ORN': 'Algeria',
    'ORY': 'France',
    'OSL': 'Norway',
    'OST': 'Belgium',
    'OTBD': 'Qatar',
    'OTP': 'Romania',
    'OVB': 'Russia',
    'OVD': 'Spain',
    'OZZ': 'Saudi Arabia',
    'PAD': 'Germany',
    'PDL': 'Portugal',
    'PEE': 'Russia',
    'PEG': 'Italy',
    'PEK': 'China',
    'PHL': 'United States',
    'PIE': 'United States',
    'PIK': 'United Kingdom',
    'PMI': 'Spain',
    'PMO': 'Italy',
    'PNA': 'Spain',
    'PNE': 'United States',
    'POZ': 'Poland',
    'PRG': 'Czech Republic',
    'PSA': 'Italy',
    'PSM': 'United States',
    'PSR': 'Italy',
    'PUJ': 'Dominican Republic',
    'PVG': 'China',
    'QWC': 'Germany',
    'RAK': 'Morocco',
    'RBA': 'Morocco',
    'REK': 'Iceland',
    'RGS': 'Spain',
    'RHE': 'France',
    'RHO': 'Greece',
    'RIX': 'Latvia',
    'RLG': 'Germany',
    'RNL': 'Netherlands',
    'RNS': 'France',
    'ROV': 'Russia',
    'RTM': 'Netherlands',
    'RVN': 'Sweden',
    'RYG': 'Norway',
    'SAN': 'United States',
    'SAO': 'Brazil',
    'SAW': 'Turkey',
    'SCL': 'Chile',
    'SCQ': 'Spain',
    'SCW': 'Russia',
    'SDR': 'Spain',
    'SDV': 'Israel',
    'SDY': 'United States',
    'SEA': 'United States',
    'SEN': 'United Kingdom',
    'SFO': 'United States',
    'SFX': 'France',
    'SGC': 'Russia',
    'SGD': 'Denmark',
    'SIA': 'Italy',
    'SID': 'Cape Verde',
    'SIN': 'Singapore',
    'SJJ': 'Bosnia and Herzegovina',
    'SJO': 'Costa Rica',
    'SJU': 'United States',
    'SKBO': 'Colombia',
    'SKG': 'Greece',
    'SKP': 'North Macedonia',
    'SLM': 'Spain',
    'SOF': 'Bulgaria',
    'SOU': 'United Kingdom',
    'SPC': 'Spain',
    'SPU': 'Croatia',
    'STI': 'Dominican Republic',
    'STN': 'United Kingdom',
    'STR': 'Germany',
    'STU': 'Germany',
    'SUF': 'Italy',
    'SVG': 'Norway',
    'SVO': 'Russia',
    'SVQ': 'Spain',
    'SVX': 'Russia',
    'SXB': 'France',
    'SXF': 'Germany',
    'SZG': 'Austria',
    'TFN': 'Spain',
    'TFS': 'Spain',
    'TGM': 'Romania',
    'THF': 'Germany',
    'TJM': 'Russia',
    'TLL': 'Estonia',
    'TLS': 'France',
    'TLV': 'Israel',
    'TNG': 'Morocco',
    'TOF': 'Russia',
    'TOJ': 'Spain',
    'TRD': 'Norway',
    'TRF': 'Norway',
    'TRN': 'Italy',
    'TRS': 'Italy',
    'TSF': 'Italy',
    'TSR': 'Romania',
    'TTN': 'United States',
    'TUF': 'France',
    'TUN': 'Tunisia',
    'TXL': 'Germany',
    'UFA': 'Russia',
    'VBS': 'Italy',
    'VCE': 'Italy',
    'VDA': 'Israel',
    'VGO': 'Spain',
    'VIE': 'Austria',
    'VKO': 'Russia',
    'VLC': 'Spain',
    'VLL': 'Spain',
    'VNC': 'Italy',
    'VNO': 'Lithuania',
    'VOG': 'Russia',
    'VOZ': 'Russia',
    'VRN': 'Italy',
    'WAW': 'Poland',
    'WMI': 'Poland',
    'WRO': 'Poland',
    'XRY': 'Spain',
    'XSP': 'Singapore',
    'XYT': 'France',
    'YMQ': 'Canada',
    'YMX': 'Canada',
    'YUL': 'Canada',
    'YYZ': 'Canada',
    'ZAD': 'Croatia',
    'ZAG': 'Croatia',
    'ZHR': 'Switzerland',
    'ZRH': 'Switzerland',
    'ZZZ': 'Unknown'
}

country_to_continent = {
    'Denmark': 'Europe',
    'United Arab Emirates': 'Asia',
    'Nigeria': 'Africa',
    'United Kingdom': 'Europe',
    'Ghana': 'Africa',
    'Spain': 'Europe',
    'United States': 'North America',
    'Turkey': 'Europe',
    'Italy': 'Europe',
    'Algeria': 'Africa',
    'Jordan': 'Asia',
    'Netherlands': 'Europe',
    'Belgium': 'Europe',
    'Russia': 'Europe',
    'Sweden': 'Europe',
    'Romania': 'Europe',
    'Greece': 'Europe',
    'Costa Rica': 'North America',
    'Serbia': 'Europe',
    'Ethiopia': 'Africa',
    'Germany': 'Europe',
    'France': 'Europe',
    'Israel': 'Asia',
    'Lebanon': 'Asia',
    'Norway': 'Europe',
    'Gambia': 'Africa',
    'China': 'Asia',
    'Thailand': 'Asia',
    'Colombia': 'South America',
    'Belarus': 'Europe',
    'Switzerland': 'Europe',
    'Slovakia': 'Europe',
    'Hungary': 'Europe',
    'Argentina': 'South America',
    'Poland': 'Europe',
    'Republic of the Congo': 'Africa',
    'Egypt': 'Africa',
    'Venezuela': 'South America',
    'Morocco': 'Africa',
    'Croatia': 'Europe',
    'Tunisia': 'Africa',
    'Senegal': 'Africa',
    'Qatar': 'Asia',
    'Ukraine': 'Europe',
    'Ireland': 'Europe',
    'Western Sahara': 'Africa',
    'Armenia': 'Asia',
    'Faroe Islands': 'Europe',
    'Portugal': 'Europe',
    'Brazil': 'South America',
    'Azerbaijan': 'Asia',
    'Cuba': 'South America',
    'Finland': 'Europe',
    'Hong Kong': 'Asia',
    'South Korea': 'Asia',
    'Iran': 'Asia',
    'Pakistan': 'Asia',
    'South Africa': 'Africa',
    'Iceland': 'Europe',
    'Rwanda': 'Africa',
    'Moldova': 'Europe',
    'Malaysia': 'Asia',
    'Lithuania': 'Europe',
    'Cyprus': 'Asia',
    'Peru': 'South America',
    'Slovenia': 'Europe',
    'Austria': 'Europe',
    'Luxembourg': 'Europe',
    'Mexico': 'North America',
    'Malta': 'Europe',
    'Uruguay': 'South America',
    'Japan': 'Asia',
    'Saudi Arabia': 'Asia',
    'Czech Republic': 'Europe',
    'Dominican Republic': 'North America',
    'Latvia': 'Europe',
    'Chile': 'South America',
    'Cape Verde': 'Africa',
    'Singapore': 'Asia',
    'Bosnia and Herzegovina': 'Europe',
    'North Macedonia': 'Europe',
    'Bulgaria': 'Europe',
    'Estonia': 'Europe',
    'Canada': 'North America',
    'Unknown': 'Unknown'
}
